### ISSUE TITLE
Default middleware stack

### ISSUE THREAD

**Issue by greg0ire** [swarrot/SwarrotBundle#100]
I think it would be handy to be able to define a default middleware stack that would server as a basis for every consumer. I discovered the `swarrot.processor.ack` and I can't imagine why one would ever not use it. I can provide a PR for that.

**Comment by odolbeau** [comment]
To be honest, I don't know.
I also use this processor with most of my consumers. I also use near everytime the same middleware stack (retry, signal handler & so on). At the end, the configuration I use is very similar to the [reference configuration](https://github.com/swarrot/SwarrotBundle#configuration-reference) which could be the default one.
*My* default one in fact. If you don't use one of the processor I use, you'll have to override the whole middleware stack.
If we had this processor (and only this processor) in the default middleware stack, I'll this have to override this config to fit my needs.
As you can see, I don't think it's that useful to define a default middleware stack which will be override by most of swarrot users anyway.

**Comment by greg0ire** [comment]
@odolbeau I don't mean to contribute a default middleware stack. I want to give you the possibility to define *your* middleware stack once, and reuse it as a basis (meaning you could add to it).

**Comment by odolbeau** [comment]
In this case, I don't really understand what you want to do.
Do you use the same middleware stack for different consumers? If it's the case, why did you choose to use different consumers?

**Comment by greg0ire** [comment]
@odolbeau I'm doing very different jobs, based on the same kind of message => I need several consumers, it's the best practice. I also plan to add to a new consumer, that will consume a very different kind of message. In that case, I will also need a separate consumer, but in all cases, I will use the `swarrot.processor.ack` processor.

**Comment by greg0ire** [comment]
I have a slight preference for the first solution, the second one might be overkill. What do you think?

**Comment by greg0ire** [comment]
> Do you use the same middleware stack for different consumers?

To clarify, yes, but the inner processor (the one I write) is not necessarily the same. I say not necessarily because I also happen to have two consumer with exactly the same stack, but a different vhost : there is a "real vhost", from where legit events come (produced by a legacy django app), that I have read-only access on, and a "local vhost", that produces similar events, so that I can do a bulk import by producing many events if I need to (from my non-legacy symfony app).

**Comment by odolbeau** [comment]
If I understand well, you would like to have a new configuration key like `default_middleware_stack` which will be used by default for all your consumers.
As soon as you change this stack, you have to override it for the consumer you want?
So it will be useful only if you have n consumers with the exact same middleware stack?

Did I understand well?

**Comment by greg0ire** [comment]
> If I understand well, you would like to have a new configuration key like default_middleware_stack which will be used by default for all your consumers.

Yes, that's the first solution I described.

>  As soon as you change this stack, you have to override it for the consumer you want?

You could complement it on a consumer-per-consumer basis, but you wouldn't be able to override it. So if there is an item you want for 90% of your consumers, you can't add it to the default stack (which would maybe better be named as `base_stack` ?)

>  So it will be useful only if you have n consumers with the exact same middleware stack?

It would be useful only if you have n consumer with the exact same base stack : 

```
- runner1:
    - my_processor_that_does_a_specific_job_that_I_wrote_in_my_project
    - ackprocessor
    - memory_processor
    - retry_processor
    - signal_handler_processor
    - some_other_processor
- runner2:
    - schwift_schmeckles_processor
    - ackprocessor
    - memory_processor
    - retry_processor
    - signal_handler_processor
    - some_other_processor_that_I_want_here
    - some_other_processor_that_I_want_here_too
- runner3:
    - copy_photos_processor
    - ackprocessor
    - memory_processor
    - retry_processor
    - signal_handler_processor
```

Here, the `default_stack` or `base_stack` would be

```
    - ackprocessor
    - memory_processor
    - retry_processor
    - signal_handler_processor
```

It may or may not be augmented with other processor.
With solution 1, you can't define a runner that does not have the memory
processor, for instance.

**Comment by greg0ire** [comment]
# Solution 3: chain configurator

```
swarrot:
    default_middleware_stack: # if not empty, a service instance of ChainConfigurator will be created (swarrot.processor.chain)
        - configurator: swarrot.process.ack
        - configurator: another.processor
        - configurator: you.get.the.idea
    consumers:
        no_additional_processor_consumer:
            processor: innermost_processor
            middleware_stack:
                - configurator: swarrot.processor.chain
        consumer_with_extra_processor_at_the_top_of_the_stack:
            processor: innermost_processor
            middleware_stack:
                - configurator: swarrot.processor.chain
                - configurator: additional_configurator
        consumer_with_extra_processor_at_the_bottom_of_the_stack:
            processor: innermost_processor
            middleware_stack:
                - configurator: additional_configurator
                - configurator: swarrot.processor.chain
```
