### ISSUE TITLE
Command options are ignored when extra config is set

### ISSUE THREAD

**Issue by notFloran** [swarrot/SwarrotBundle#101]
I have defined a comsumer with the following extras:

```
            extras:
                max_messages: 100
                max_execution_time: 300
``` 

And I want to consume only one message so I execute the following  command : 

```
sf swarrot:consume:voip_valorize_call citadel_voip_valorize_calls --max-messages 1
```

But the option `max-messages`is ignored : 

```
[MaxMessages] Max messages have been reached (100)
```

I think the problem came from this line : https://github.com/swarrot/SwarrotBundle/blob/master/Command/SwarrotCommand.php#L120

The `+` ignore already defined config, we can use a `array_merge`to fix that.

**Comment by odolbeau** [comment]
Hi.
Could you please paste your whole configuration?
When you want to add `extras` config, it should be put under the right processor. In your case, I think you're adding extra configuration for your consumer (which doesn't know how to deal with those options).
You can take a at the [configuration reference](https://github.com/swarrot/SwarrotBundle#configuration-reference) to have an example.

**Comment by notFloran** [comment]
Hi !

My config : 

``` 
swarrot:
    provider: pecl
    default_connection: rabbitmq
    default_command: swarrot.command.base
    connections:
        rabbitmq:
            host: "%rabbitmq_host%"
            port: "%rabbitmq_port%"
            login: "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost: "%rabbitmq_vhost%"
    consumers:
        voip_valorize_call:
            processor: voip.processor.valorize_call
            middleware_stack: # order matter
                - configurator: swarrot.processor.signal_handler
                - configurator: swarrot.processor.max_messages
                - configurator: swarrot.processor.max_execution_time
                - configurator: swarrot.processor.exception_catcher
                - configurator: app.processor_configurator.sentry_exception_catcher
                - configurator: swarrot.processor.ack
            extras:
                max_messages: 100
                max_execution_time: 300
```

The "extras" config works: when I execute the swarrot command without options 100 messages are handled.
But when I want to override this config with the `--max-messages 1` option of the swarrot command, that doesn't works : 100 messages are handled, not 1

**Comment by odolbeau** [comment]
Your config should looks like this:
```yaml
swarrot:
    provider: pecl
    default_connection: rabbitmq
    default_command: swarrot.command.base
    connections:
        rabbitmq:
            host: "%rabbitmq_host%"
            port: "%rabbitmq_port%"
            login: "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost: "%rabbitmq_vhost%"
    consumers:
        voip_valorize_call:
            processor: voip.processor.valorize_call
            middleware_stack: # order matter
                - configurator: swarrot.processor.signal_handler
                - configurator: swarrot.processor.max_messages
                  extras:
                      max_messages: 100
                - configurator: swarrot.processor.max_execution_time
                  extras:
                      max_execution_time: 300
                - configurator: swarrot.processor.exception_catcher
                - configurator: app.processor_configurator.sentry_exception_catcher
                - configurator: swarrot.processor.ack
```

Each extra config should be attached to the relevant configurator.
Can you confirm it works with this config?

I'll try to figure out why those options partly work when they are put under the customer instead of the right configurator.

BTW, I see that you're using a `sentry_exception_catcher`. Is it possible to share your code? Maybe in a gist if you think it's not something which can be merged in swarrot?
