### ISSUE TITLE
Problem with symfony/dotenv

### ISSUE THREAD

**Issue by SZelenko** [swarrot/SwarrotBundle#131]
My .env
```ruby
SWARROT_RABBIT_MQ_HOST=rabbitmq
SWARROT_RABBIT_MQ_PORT=15672
SWARROT_RABBIT_MQ_LOGIN=admin
SWARROT_RABBIT_MQ_PASSWORD=admin
```
And has configuration:
```yaml
swarrot:
    connections:
        rabbitmq:
            host: %env(SWARROT_RABBIT_MQ_HOST)%
            port: %env(SWARROT_RABBIT_MQ_PORT)%
            login: %env(SWARROT_RABBIT_MQ_LOGIN)%
            password: %env(SWARROT_RABBIT_MQ_PASSWORD)%
```

On try clear cache i got:
Invalid type for path "swarrot.connections.rabbitmq.port". Expected int, but got string.

As i know dotenv uses strings only (like bash etc..)

I think ``` ->integerNode('port')->defaultValue(5672)->end() ```  should be changed to scalar with normalization to int.

_PS.: Used symfony/skeleton 3.4_
