### ISSUE TITLE
Set 'retry_exchange' option

### ISSUE THREAD

**Issue by nbremont** [swarrot/SwarrotBundle#138]
Hi,

I want to set 'retry_exchange' extra options for retry processor, but i have an error when i want to execute generated consumer. My context is in SwarrotBundle v1.5.1

ex: 
```
In OptionsResolver.php line 667:

  The option "retry_exchange" does not exist. Defined options are: "connection", "max_execution_time", "poll_interval", "queue", "requeue_on_error", "retry_attempts", "retry_fail_log_levels_map", "retr
  y_key_pattern", "retry_log_levels_map".
```

This is my configuration:
```
swarrot:
    consumers:
        order_create_consumer:
            processor: onepoint.order.create.processor
            middleware_stack:
                 - configurator: swarrot.processor.exception_catcher
                 - configurator: swarrot.processor.ack
                 - configurator: swarrot.processor.max_execution_time
                 - configurator: swarrot.processor.retry
            extras:
              max_execution_time: 120
              retry_exchange: 'toto'
              retry_attempts: 2
```

Do you have any idea ?
