### ISSUE TITLE
dot in messages-types are lost in the command help

### ISSUE THREAD

**Issue by lyrixx** [swarrot/SwarrotBundle#153]
For exemple:
```
swarrot:
    messages_types:
        crawler.update_db:
            exchange: 'redirectionio'
            routing_key: 'crawler.update_db'
```

but the `--help` give that:

```
Description:
  Consume message of type "crawler_update_db" from a given queue
```

The dot has been replaced by and underscore
