### ISSUE TITLE
Why the message type is not used as the queue name by default

### ISSUE THREAD

**Issue by lyrixx** [swarrot/SwarrotBundle#154]
I know this is not necessary true, but it could be so useful.

Given this configuration:
```
swarrot:
    messages_types:
        crawler.update_db:
            exchange: 'redirectionio'
            routing_key: 'crawler.update_db'
```
Instead of 
```
bin/console bin/console  swarrot:consume:crawler_update_db crawler.update_db
```
I would like to run 
```
bin/console bin/console  swarrot:consume:crawler_update_db
```
