### ISSUE TITLE
Upgrade Doctrine dependencies

### ISSUE THREAD

**Issue by TakTaki** [swarrot/SwarrotBundle#208]
Hello,

I've recently updated doctrine/common to 3.1.0 and composer didn't rise the fact that SwarrotBundle was using ^2.9.
As I'm using the configuration 
```yaml
swarrot:
    consumers:
        my_consumer:
            middleware_stack: 
                 - configurator: swarrot.processor.doctrine_object_manager
```
this rise me the error of using the wrong `ManagerRegistry` (as path changed in doctrine).

Is there a way to fix this ? Am I doing something wrong ? 

Thanks
