### ISSUE TITLE
Multiple hosts support

### ISSUE THREAD

**Issue by yun548** [swarrot/SwarrotBundle#213]
It seems that `amqp_lib` supports multiple hosts for [a same connection](https://github.com/php-amqplib/php-amqplib#multiple-hosts-connections), is this supported by the bundle configuration when using `amqp_lib` ? I can't seem to find an example with the reference ? 

I'm imagining configuration would be something along these lines : 
```
swarrot:
    provider: amqp_lib
    default_connection: rabbitmq
    default_command: swarrot.command.base
    connections:
        rabbitmq:
            url: "amqp://%rabbitmq_user%:%rabbitmq_password%@%rabbitmq_host1%&%rabbitmq_host2%:%rabbitmq_port%"
            vhost: '/'
```
