### ISSUE TITLE
Custom processor stack

### ISSUE THREAD

**Issue by joelwurtz** [swarrot/SwarrotBundle#81]
Actually the processor stack definition is highly coupled to commands and other stuff, so adding our own processor into the mix imply to rewrite the whole command stuff.

My proposal would introduce a new interface : `ProcessorFactoryInterface` and a new way of configuring the processor stack : 

```
processors_stack:
    retry: retry.processor.factory
    my_processor: my_processor_factory_service
    another_processor: another_processor_service
```

Each value in the processors_stack list would be a service id representing a `ProcessorFactoryInterface` service or a `ProcessorInterface` service

If it's a `ProcessorInterface` then the processor is just add to the stack, if it's a factory it will add input option / argument to the command and generate the service depending on the command options value.

So the `ProcessorFactoryInterface` would look like this : 

```
interface ProcessorFactoryInterface
{
    /**
     * Create service given a specific input
     */
    public function create(InputInterface $input);

    /**
     * Add input argument / option to the command
     */
    public function configure(CommandInterface $command);
}
```

WDYT ?

**Comment by odolbeau** [comment]
:+1: 

You're right, today it's not possible to create its own stack without rewriting the whole command. :)

**Comment by jderusse** [comment]
I create a `SwarrotExtraBundle` which allow such configuration
```
swarrot_extra:
    default_connection: default
    consumers:
        update:
            processors:
                swarrot_extra.processors.message_stack: ~

                swarrot_extra.processors.signal_handler: ~
                swarrot_extra.processors.max_messages: ~
                swarrot_extra.processors.max_execution_time: ~
                swarrot_extra.processors.doctrine_connection:
                swarrot_extra.processors.doctrine_object_manager:
                app.processors.socketio: ~

                swarrot_extra.processors.exception_catcher: ~

                swarrot_extra.processors.ack: ~
                swarrot_extra.processors.retry:
                    extras:
                        retry_attempts: %retry_attempts%
                        retry_key_pattern: '%%queue%%_retry'

                rechart_messaging.processors.event: ~
            queue: document.update
```
Where you're able to change parameters and order of each processor.

@odolbeau : Are you interested by merging this feature (BC break) in you this bundle ?
